name: 'Install dependencies'
description: ''

defaults:
  run:
    working-directory: modern-web-app
runs:
  using: 'composite'
  steps:
    - name: Setup Node 🕸️
      uses: actions/setup-node@v2
      with:
        node-version: 16.16

    - name: Cache node modules ✨
      uses: actions/cache@v2
      id: cache-modules
      env:
        cache-name: cache-node-${{ matrix.node }}-modules
      with:
        path: ./node_modules
        key: ${{ runner.os }}-cache-${{ env.cache-name }}-${{ hashFiles('./yarn.lock') }}
        restore-keys: ${{ runner.os }}-cache-${{ env.cache-name }}-

    - name: Install Dependencies 🔧
      if: steps.cache-modules.outputs.cache-hit != 'true'
      shell: bash
      run: |
        yarn install --frozen-lockfile

    - name: Cache Playwright binaries ✨
    - uses: actions/cache@v3
      id: playwright-cache
      with:
        path: '~/.cache/ms-playwright'
        key: '${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}'
        restore-keys: ${{ runner.os }}-playwright-

    - name: Install Playwright with dependencies
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps

    - name: Install Playwright's dependencies
      if: steps.playwright-cache.outputs.cache-hit == 'true'
      run: npx playwright install-deps